services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - diary-backend-network

  spring-boot-server:
    depends_on:
      mysqldb:
        condition: service_started
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-boot-server:latest
    restart: on-failure
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
          "spring.datasource.username" : "$MYSQLDB_ROOT_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.hibernate.ddl-auto" : "create",
          "server.port" : "$SPRING_LOCAL_PORT"
        }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - diary-backend-network

volumes:
  db:

networks:
  diary-backend-network: